"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
from os import waitpid, fork

if sys.platform == 'darwin':
    if (pid := fork()) == 0:
        APP = ['shrink.py']
        DATA_FILES = ['model/haarcascade_frontalface_default.xml']
        OPTIONS = {'iconfile': 'resources/shrink.icns'}
        setup(
            app=APP,
            data_files=DATA_FILES,
            options={'py2app': OPTIONS, },
            setup_requires=['py2app'],
        )
    else:
        waitpid(pid, 0)  # building 2 at once doesn't work
        APP = ['facedetect.py']
        DATA_FILES = ['model/haarcascade_frontalface_default.xml',]
        OPTIONS = {'iconfile': 'resources/fd.icns'}
        setup(
            app=APP,
            data_files=DATA_FILES,
            options={'py2app': OPTIONS, },
            setup_requires=['py2app'],
        )
elif sys.platform == 'windows':
    if (pid := fork()) == 0:
        setup(windows=[
            {
                "script": "shrink.py",
                "icon_resources": [(1, "resources/shrink.ico")]
            }
        ],)
    else:
        waitpid(pid, 0)  # building 2 at once doesn't work
        setup(windows=[[
            {
                "script": "facedetect.py",
                "icon_resources": [(1, "resources/fd.ico")]
            }
        ],])
